CONFIG_GPIO=y
CONFIG_SPI=y        #SPI相關
CONFIG_SENSOR=y     #sensor相關
#CONFIG_ADXL345=y   #spi無須添加
CONFIG_LED=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_MULTITHREADING=y     #多執行續相關
CONFIG_CBPRINTF_FP_SUPPORT=y
